version: '3.8'

services:
  db:
    image: mysql
    container_name: client_api-mysql-1
    restart: always
    environment:
      MYSQL_DATABASE: "client_api_db"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"